// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(

	//////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
	input 		          		ADC_CLK_10,
`endif
	//////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
	input 		          		MAX10_CLK1_50,
`endif
	//////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
	input 		          		MAX10_CLK2_50,
`endif

	//////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,
`endif

	//////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
	output		     [7:0]		HEX0,
`endif
`ifdef ENABLE_HEX1
	output		     [7:0]		HEX1,
`endif
`ifdef ENABLE_HEX2
	output		     [7:0]		HEX2,
`endif
`ifdef ENABLE_HEX3
	output		     [7:0]		HEX3,
`endif
`ifdef ENABLE_HEX4
	output		     [7:0]		HEX4,
`endif
`ifdef ENABLE_HEX5
	output		     [7:0]		HEX5,
`endif

	//////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
	input 		     [1:0]		KEY,
`endif

	//////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
	output		     [9:0]		LEDR,
`endif

	//////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
	input 		     [9:0]		SW,
`endif

	//////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,
`endif

	//////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO,
`endif

	//////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,
`endif

	//////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
	inout 		    [35:0]		GPIO
`endif
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire pll_rst, rst_n	;
wire sys_clk, spi_clk;
wire [7:0] rd_data;
wire ack;

assign rst_n 	= KEY[0];
assign pll_rst = ~rst_n;
assign LEDR = {pll_locked, ack, data};

wire spi_oe_o;

wire sdo;
assign GSENSOR_SDI = spi_oe_o ? sdo : 1'bZ;

wire front_detector;
reg  signal_delay;

always @(posedge sys_clk) begin
		signal_delay <= KEY[1];
end

assign front_detector = ~KEY[1] & signal_delay;

reg [7:0] data;

always @(posedge sys_clk or negedge rst_n) begin
		if (~rst_n)	data <= 0; else
		if (ack) 	data <= rd_data;
end
//=======================================================
//  Structural coding
//=======================================================

pll	pll_inst (
	.areset 	( pll_rst 			),
	.inclk0 	( MAX10_CLK1_50 	),
	.c0 		( sys_clk 			),
	.c1 		( spi_clk 			),
	.locked 	( pll_locked 		)
	);

spi_phy spi_phy_inst(
    .rst_ni    	( rst_n	 	),
    .clk_i     	( sys_clk 	),  // max 5MHz for ADXL345 sensor
    .spi_clk_i 	( spi_clk 	),  // same frequency as clk_i, 220 deg phase offset

    // Parallel request-acknowledge interface (sampled with clk_i)
    .req_i     	( front_detector 	),
    .rw_ni     	( 1 			),  // 1=read, 0=write
    .addr_i    	( SW[5:0] 	),
    .wr_data_i 	( 0 			),
    .ack_o     	( ack			),
    .rd_data_o 	( rd_data 	),

    // SPI interface
    .spi_cs_no 	( GSENSOR_CS_N	),
    .spi_clk_o 	( GSENSOR_SCLK	),
    .spi_data_o	( sdo				),
    .spi_data_i	( GSENSOR_SDI	),
    .spi_oe_o  	( spi_oe_o 		)    // control 3-state buffer for 3-wire SPI mode 
);

endmodule
